baseURL = "https://bigclown.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableKinds = ["RSS", "sitemap"]
languageCode = "en"
title = "BigClown"

[blackfriday]
fractions = false

[Languages]
[Languages.en]
weight = 1
languageName = "English"
[Languages.cs]
weight = 2
languageName = "Čeština"
