baseURL = "https://www.bigclown.com/"
disableKinds = ["RSS", "sitemap"]
languageCode = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true
title = "BigClown"

[blackfriday]
smartypants = false

[params]
menuNames = ["main"]
productionURL = "https://www.bigclown.com"
