baseURL = "https://www.bigclown.com/"
languageCode = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true
title = "BigClown"

[blackfriday]
smartypants = false

[params]
menuNames = ["main"]
productionURL = "https://www.bigclown.com"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
