baseURL = "https://www.bigclown.com/"
DefaultContentLanguage = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  menuNames = ["main","doc"]
  homeURL = "/"
  shopURL = "https://shop.bigclown.com/?currency=EUR"
  productionURL = "https://www.bigclown.com"

[languages]
  [languages.en]
    LanguageName = "ENG"
    weight = 1
    [languages.en.params]
      baseURL = "/"
      shopURL = "https://shop.bigclown.com/?currency=EUR"
  [languages.cs]
    LanguageName = "CZE"
    weight = 2
    [languages.cs.params]
      baseURL = "/cs/"
      shopURL = "https://shop.bigclown.com/?currency=CZK"
      homeURL = "/cs/"

[menu]

[[languages.en.menu.doc]]
  identifier = "intro"
  name = "Intro"
  url = "/doc/"
  weight = 1

[[languages.en.menu.doc]]
  identifier = "basics"
  name = "Basics"
  url = "/doc/basics/quick-start-guide/"
  weight = 10

[[languages.en.menu.doc]]
  identifier = "tutorials"
  name = "Tutorials"
  url = "/doc/tutorials/raspberry-pi-tutorial/"
  weight = 20

[[languages.en.menu.doc]]
  identifier = "projects"
  name = "Projects"
  url = "/doc/projects/radio-door-sensor/"
  weight = 30

[[languages.en.menu.doc]]
  identifier = "interfaces"
  name = "Interfaces"
  url = "/doc/interfaces/mqtt-protocol/"
  weight = 40

[[languages.en.menu.doc]]
  identifier = "integrations"
  name = "Integrations"
  url = "/doc/integrations/grafana-for-visualization/"
  weight = 50

[[languages.en.menu.doc]]
  identifier = "hardware"
  name = "Hardware"
  url = "/doc/hardware/basic-principles/"
  weight = 60

[[languages.en.menu.doc]]
  identifier = "firmware"
  name = "Firmware"
  url = "/doc/firmware/basic-overview/"
  weight = 70

[[languages.en.menu.doc]]
  identifier = "tools"
  name = "Tools"
  url = "/doc/tools/bcf/"
  weight = 80

[[languages.en.menu.doc]]
  identifier = "documentation"
  name = "Documentation"
  url = "/doc/documentation/contribution-setup/"
  weight = 90


  [[languages.en.menu.main]]
    identifier = "intro"
    name = "Intro"
    url = "/doc/"
    weight = 1
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "basics"
    name = "Basics"
    url = "/doc/basics/quick-start-guide/"
    weight = 10
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "/doc/tutorials/raspberry-pi-tutorial/"
    weight = 20
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/doc/projects/radio-door-sensor/"
    weight = 30
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "interfaces"
    name = "Interfaces"
    url = "/doc/interfaces/mqtt-protocol/"
    weight = 40
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "integrations"
    name = "Integrations"
    url = "/doc/integrations/grafana-for-visualization/"
    weight = 50
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "hardware"
    name = "Hardware"
    url = "/doc/hardware/basic-principles/"
    weight = 60
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "firmware"
    name = "Firmware"
    url = "/doc/firmware/basic-overview/"
    weight = 70
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "tools"
    name = "Tools"
    url = "/doc/tools/bcf/"
    weight = 80
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "/doc/documentation/contribution-setup/"
    weight = 90
    parent = "learn"

  [[languages.en.menu.main]]
    identifier = "support"
    name = "Support"
    pre = ""
    url = "/support/"
    weight = 400

  [[languages.en.menu.main]]
    identifier = "github"
    name = "GitHub"
    parent = "support"
    pre = ""
    post = "_blank"
    url = "https://github.com/bigclownlabs"
    weight = 300

  [[languages.en.menu.main]]
    identifier = "forum"
    name = "Forum"
    parent = "support"
    pre = ""
    post = "_blank"
    url = "https://forum.bigclown.com"
    weight = 100

  [[languages.cs.menu.main]]
    identifier = "support"
    name = "Podpora"
    pre = ""
    url = "/cs/support/"
    weight = 400

  [[languages.cs.menu.main]]
    identifier = "github"
    name = "GitHub"
    parent = "support"
    pre = ""
    post = "_blank"
    url = "https://github.com/bigclownlabs"
    weight = 100

  [[languages.cs.menu.main]]
    identifier = "forum"
    name = "Fórum"
    parent = "support"
    pre = ""
    post = "_blank"
    url = "https://forum.bigclown.com"
    weight = 300

[blackfriday]
smartypants = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

  [taxonomies]
    tag = "tags"
